var annotated =
[
    [ "Application", "class_application.html", "class_application" ],
    [ "Button", "class_button.html", "class_button" ],
    [ "Canvas", "class_canvas.html", "class_canvas" ],
    [ "Color", "class_color.html", "class_color" ],
    [ "Event", "class_event.html", "class_event" ],
    [ "Font", "class_font.html", "class_font" ],
    [ "GraphicsAnimation", "class_graphics_animation.html", "class_graphics_animation" ],
    [ "GraphicsBlinkAnimation", "class_graphics_blink_animation.html", "class_graphics_blink_animation" ],
    [ "GraphicsCircle", "class_graphics_circle.html", "class_graphics_circle" ],
    [ "GraphicsEllipse", "class_graphics_ellipse.html", "class_graphics_ellipse" ],
    [ "GraphicsItem", "class_graphics_item.html", "class_graphics_item" ],
    [ "GraphicsLine", "class_graphics_line.html", "class_graphics_line" ],
    [ "GraphicsPoint", "class_graphics_point.html", "class_graphics_point" ],
    [ "GraphicsPolygon", "class_graphics_polygon.html", "class_graphics_polygon" ],
    [ "GraphicsRectangle", "class_graphics_rectangle.html", "class_graphics_rectangle" ],
    [ "GraphicsShape", "class_graphics_shape.html", "class_graphics_shape" ],
    [ "GraphicsSquare", "class_graphics_square.html", "class_graphics_square" ],
    [ "GraphicsText", "class_graphics_text.html", "class_graphics_text" ],
    [ "GraphicsTriangle", "class_graphics_triangle.html", "class_graphics_triangle" ],
    [ "GroupPoints", "class_group_points.html", "class_group_points" ],
    [ "KeyEvent", "class_key_event.html", "class_key_event" ],
    [ "Label", "class_label.html", "class_label" ],
    [ "Layout", "class_layout.html", "class_layout" ],
    [ "LineEdit", "class_line_edit.html", "class_line_edit" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "MouseEvent", "class_mouse_event.html", "class_mouse_event" ],
    [ "Point", "class_point.html", "class_point" ],
    [ "ToolsWindow", "class_tools_window.html", "class_tools_window" ],
    [ "ToolsWindows", "class_tools_windows.html", "class_tools_windows" ],
    [ "Widget", "class_widget.html", "class_widget" ],
    [ "Window", "class_window.html", "class_window" ]
];