var files =
[
    [ "Application.cpp", "_application_8cpp_source.html", null ],
    [ "Application.hpp", "_application_8hpp_source.html", null ],
    [ "Button.cpp", "_button_8cpp_source.html", null ],
    [ "Button.hpp", "_button_8hpp.html", null ],
    [ "Canvas.cpp", "_canvas_8cpp_source.html", null ],
    [ "Canvas.hpp", "_canvas_8hpp_source.html", null ],
    [ "CMakeCCompilerId.c", "_c_make_c_compiler_id_8c_source.html", null ],
    [ "CMakeCXXCompilerId.cpp", "_c_make_c_x_x_compiler_id_8cpp_source.html", null ],
    [ "Color.cpp", "_color_8cpp_source.html", null ],
    [ "Color.hpp", "_color_8hpp.html", [
      [ "Color", "class_color.html", "class_color" ]
    ] ],
    [ "ConfigItem.cpp", "_config_item_8cpp_source.html", null ],
    [ "ConfigItem.hpp", "_config_item_8hpp.html", [
      [ "ConfigItem", "class_config_item.html", "class_config_item" ]
    ] ],
    [ "Event.cpp", "_event_8cpp_source.html", null ],
    [ "Event.hpp", "_event_8hpp.html", [
      [ "Event", "class_event.html", "class_event" ]
    ] ],
    [ "feature_tests.c", "feature__tests_8c_source.html", null ],
    [ "feature_tests.cxx", "feature__tests_8cxx_source.html", null ],
    [ "Font.cpp", "_font_8cpp_source.html", null ],
    [ "Font.hpp", "_font_8hpp_source.html", null ],
    [ "GraphicsAnimation.cpp", "_graphics_animation_8cpp_source.html", null ],
    [ "GraphicsAnimation.hpp", "_graphics_animation_8hpp_source.html", null ],
    [ "GraphicsBlinkAnimation.cpp", "_graphics_blink_animation_8cpp_source.html", null ],
    [ "GraphicsBlinkAnimation.hpp", "_graphics_blink_animation_8hpp_source.html", null ],
    [ "GraphicsCircle.cpp", "_graphics_circle_8cpp_source.html", null ],
    [ "GraphicsCircle.hpp", "_graphics_circle_8hpp_source.html", null ],
    [ "GraphicsEllipse.cpp", "_graphics_ellipse_8cpp_source.html", null ],
    [ "GraphicsEllipse.hpp", "_graphics_ellipse_8hpp_source.html", null ],
    [ "GraphicsFactory.cpp", "_graphics_factory_8cpp_source.html", null ],
    [ "GraphicsFactory.hpp", "_graphics_factory_8hpp_source.html", null ],
    [ "GraphicsItem.cpp", "_graphics_item_8cpp_source.html", null ],
    [ "GraphicsItem.hpp", "_graphics_item_8hpp_source.html", null ],
    [ "GraphicsLine.cpp", "_graphics_line_8cpp_source.html", null ],
    [ "GraphicsLine.hpp", "_graphics_line_8hpp_source.html", null ],
    [ "GraphicsPoint.cpp", "_graphics_point_8cpp_source.html", null ],
    [ "GraphicsPoint.hpp", "_graphics_point_8hpp_source.html", null ],
    [ "GraphicsPolygon.cpp", "_graphics_polygon_8cpp_source.html", null ],
    [ "GraphicsPolygon.hpp", "_graphics_polygon_8hpp_source.html", null ],
    [ "GraphicsRectangle.cpp", "_graphics_rectangle_8cpp_source.html", null ],
    [ "GraphicsRectangle.hpp", "_graphics_rectangle_8hpp_source.html", null ],
    [ "GraphicsShape.cpp", "_graphics_shape_8cpp_source.html", null ],
    [ "GraphicsShape.hpp", "_graphics_shape_8hpp.html", null ],
    [ "GraphicsSquare.cpp", "_graphics_square_8cpp_source.html", null ],
    [ "GraphicsSquare.hpp", "_graphics_square_8hpp_source.html", null ],
    [ "GraphicsText.cpp", "_graphics_text_8cpp_source.html", null ],
    [ "GraphicsText.hpp", "_graphics_text_8hpp.html", null ],
    [ "GraphicsTriangle.cpp", "_graphics_triangle_8cpp_source.html", null ],
    [ "GraphicsTriangle.hpp", "_graphics_triangle_8hpp.html", null ],
    [ "GroupPoints.cpp", "_group_points_8cpp_source.html", null ],
    [ "GroupPoints.hpp", "_group_points_8hpp_source.html", null ],
    [ "KeyEvent.cpp", "_key_event_8cpp_source.html", null ],
    [ "KeyEvent.hpp", "_key_event_8hpp.html", [
      [ "KeyEvent", "class_key_event.html", "class_key_event" ]
    ] ],
    [ "Label.cpp", "_label_8cpp_source.html", null ],
    [ "Label.hpp", "_label_8hpp_source.html", null ],
    [ "Layout.cpp", "_layout_8cpp_source.html", null ],
    [ "Layout.hpp", "_layout_8hpp_source.html", null ],
    [ "LineEdit.cpp", "_line_edit_8cpp_source.html", null ],
    [ "LineEdit.hpp", "_line_edit_8hpp_source.html", null ],
    [ "main.cpp", "main_8cpp_source.html", null ],
    [ "MainWindow.cpp", "_main_window_8cpp_source.html", null ],
    [ "MainWindow.hpp", "_main_window_8hpp_source.html", null ],
    [ "MouseEvent.cpp", "_mouse_event_8cpp_source.html", null ],
    [ "MouseEvent.hpp", "_mouse_event_8hpp.html", [
      [ "MouseEvent", "class_mouse_event.html", "class_mouse_event" ]
    ] ],
    [ "Point.cpp", "_point_8cpp_source.html", null ],
    [ "Point.hpp", "_point_8hpp.html", "_point_8hpp" ],
    [ "SpinBox.cpp", "_spin_box_8cpp_source.html", null ],
    [ "SpinBox.hpp", "_spin_box_8hpp_source.html", null ],
    [ "ToolsWindow.cpp", "_tools_window_8cpp_source.html", null ],
    [ "ToolsWindow.hpp", "_tools_window_8hpp.html", [
      [ "ToolsWindow", "class_tools_window.html", "class_tools_window" ]
    ] ],
    [ "Widget.cpp", "_widget_8cpp_source.html", null ],
    [ "Widget.hpp", "_widget_8hpp_source.html", null ],
    [ "Window.cpp", "_window_8cpp_source.html", null ],
    [ "Window.hpp", "_window_8hpp_source.html", null ]
];